[workspace]

members = [
    "examples/binary-echo",
    "examples/clock",
    "examples/echo-server",
    "examples/randomness",
    "jamsocket",
    "jamsocket-cli",
    "jamsocket-server",
    "jamsocket-wasm",
    "jamsocket-wasm-host",
]