[package]
name = "jamsocket-server"
version = "0.1.0"
edition = "2018"

[dependencies]
actix = "0.12.0"
actix-web = "4.0.0-beta.8"
actix-web-actors = "4.0.0-beta.6"
anyhow = "1.0.42"
jamsocket = {path="../jamsocket"}
