[package]
name = "counter"
version = "0.1.0"
authors = ["Paul Butler <paulgb@gmail.com>"]
edition = "2018"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
jamsocket = {path="../../jamsocket"}
jamsocket-wasm = {path="../../jamsocket-wasm"}
