[package]
name = "native-echo"
version = "0.1.0"
edition = "2018"

[dependencies]
async-trait = "0.1.53"
stateroom = {path = "../../stateroom"}
stateroom-server = {path = "../../stateroom-server"}
tracing-subscriber = {version="0.3.1", features=["fmt", "env-filter"]}
