[package]
name = "jamsocket-cli"
version = "0.1.0"
edition = "2018"

[dependencies]
jamsocket = {path="../jamsocket"}
jamsocket-server = {path="../jamsocket-server"}
jamsocket-wasm-host = {path="../jamsocket-wasm-host"}
clap = "3.0.0-beta.2"
actix = "0.12.0"
actix-web = "4.0.0-beta.8"
actix-web-actors = "4.0.0-beta.6"
anyhow = "1.0.42"
log = "0.4.14"
env_logger = "0.9.0"
serde = { version = "1.0.127", features = ["derive"] }
toml = "0.5.8"
wasm-bindgen-cli-support = "0.2.75"
cargo_metadata = "0.14.0"

[dependencies.wasmtime]
version = "0.28.0"
default-features = false
features = ["async", "wat", "jitdump", "parallel-compilation"]
