[package]
name = "jamsocket-cli"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
jamsocket = {path="../jamsocket"}
jamsocket-server = {path="../jamsocket-server"}
jamsocket-wasm-host = {path="../jamsocket-wasm-host"}
clap = "3.0.0-beta.2"
uuid = { version = "0.8.2", features = ["v4"] }
rand = "0.8.4"
actix = "0.12.0"
actix-web = "4.0.0-beta.8"
actix-web-actors = "4.0.0-beta.6"
anyhow = "1.0.42"
serde = { version = "1.0.126", features = ["derive"] }
serde_json = "1.0.64"
async-std = "1.9.0"

[dependencies.wasmtime]
version = "0.28.0"
default-features = false
features = ["async", "wat", "jitdump", "parallel-compilation"]
