[package]
name = "stateroom-server"
version = "0.2.8"
edition = "2021"

[dependencies]
axum = { version = "0.7.5", features = ["ws"] }
dashmap = "5.5.3"
futures-util = "0.3.30"
stateroom = {path="../stateroom", version="0.2.8"}
tokio = { version = "1.37.0", features = ["rt-multi-thread"] }
