[package]
name = "clock"
version = "0.1.0"
authors = ["Paul Butler <paulgb@gmail.com>"]
edition = "2018"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
stateroom-wasm = {path="../../stateroom-wasm"}
